"""delete category field from Recipe and Product

Revision ID: 3422452442e7
Revises: 0b4815b5d1cb
Create Date: 2023-08-10 16:07:35.929759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3422452442e7'
down_revision = '0b4815b5d1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
