"""add cuisine and diet to Recipe model

Revision ID: baa6cfb678c6
Revises: 77c340fe17e6
Create Date: 2023-08-07 12:47:39.301053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa6cfb678c6'
down_revision = '77c340fe17e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('diet', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('diet')
        batch_op.drop_column('cuisine')

    # ### end Alembic commands ###
