"""divide name of product into name_ru and name_en in Product model

Revision ID: c2ba25bd430f
Revises: b05475cbea80
Create Date: 2023-08-10 16:55:57.166495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ba25bd430f'
down_revision = 'b05475cbea80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_ru', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('name_en', sa.Text(), nullable=False))
        batch_op.drop_index('ix_product_name')
        batch_op.create_index(batch_op.f('ix_product_name_en'), ['name_en'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_name_ru'), ['name_ru'], unique=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_product_name_ru'))
        batch_op.drop_index(batch_op.f('ix_product_name_en'))
        batch_op.create_index('ix_product_name', ['name'], unique=False)
        batch_op.drop_column('name_en')
        batch_op.drop_column('name_ru')

    # ### end Alembic commands ###
