"""add unit to shopping_item

Revision ID: da48f3464580
Revises: 
Create Date: 2023-07-12 12:03:52.190709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da48f3464580'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_index('ix_unit_name')

    op.drop_table('unit')
    with op.batch_alter_table('shopping_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_item', schema=None) as batch_op:
        batch_op.drop_column('unit')

    op.create_table('unit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='unit_pkey')
    )
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_index('ix_unit_name', ['name'], unique=False)

    # ### end Alembic commands ###
