"""fix migration problem

Revision ID: fd46d8774c51
Revises: 1204bf07e9c0
Create Date: 2023-07-15 00:18:46.023914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd46d8774c51'
down_revision = '1204bf07e9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_item', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
