"""add servings field to Recipe model

Revision ID: ffd055b011ee
Revises: c2ba25bd430f
Create Date: 2023-08-10 17:31:13.065228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd055b011ee'
down_revision = 'c2ba25bd430f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('ix_product_name_en')
        batch_op.create_index(batch_op.f('ix_product_name_en'), ['name_en'], unique=False)

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servings', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('servings')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_name_en'))
        batch_op.create_index('ix_product_name_en', ['name_en'], unique=False)

    # ### end Alembic commands ###
